### PR TITLE
Add color support to rgbgfx!

### LINKED ISSUE #232: Rgbgfx doesn't handle color yet
`rgbgfx` is a bit incomplete. Although there's a command line switch to export a palette file from a given PNG, and the documentation mentions "sorting colors from lightest to darkest", in actuality `rgbgfx` doesn't take color into account at all. Instead, it currently [quantizes](https://github.com/rednex/rgbds/blob/1a5c423984ca6cce1cb0b6b2100836bf4aa56e84/src/gfx/makepng.c#L153-L157) colors to the first 4 colors in the palette if the PNG is indexed, and to a preset grayscale palette if truecolor or grayscale. The documentation and [a few comments](https://github.com/rednex/rgbds/blob/1a5c423984ca6cce1cb0b6b2100836bf4aa56e84/src/gfx/makepng.c#L106-L111) suggest that this was meant to be temporary behavior until the much more complicated intended logic had been implemented. It makes sense to implement, too - currently, the palette file output does nothing (except output the preset grayscale palette) for non-indexed images, and truecolor images are often quantized in a way that assigns the same palette index to multiple colors.

There are also other color-related problems that `rgbgfx` doesn't handle properly yet - for example, transparency.

In practice, this means a few features have to be implemented:
* Truecolor and grayscale PNGs need to be analyzed to build a palette from the pixel colors.
* Generated palettes need to be sorted by relative luminance.
* All types of PNGs need to be checked for palettes with too many colors.
* Transparent pixels need to correspond to a color in the palette, as opposed to adding a new one or being thrown away.

All of these features can be implemented in a way that's backwards-compatible with *at least* pokecrystal and [Telefang](https://github.com/telefang/telefang), and with what the documentation states, so implementing / fixing these things shouldn't cause any problems.

I've implemented the missing features on my end, so I'll have a pull request coming in shortly (after a bit of extra polish)!

### PR DESCRIPTION
**Pull request by obskyr**
As it stands, `rgbgfx` doesn't handle color at all, as #232 elaborates on. This pull request fixes #232 by implementing full-fledged color support!

This patch's way to determine palette indices and colors is as following:
* PNGs with an embedded palette (PLTE chunk) simply use the indices and colors in that PLTE.
* Non-indexed PNGs with only grayscale colors in them have the shades of gray placed at appropriate indices (for 2 bits per pixel, values 0-63 get index 3, 64-127 get index 2, 128-191 get index 1, and 192-255 get index 0). In case there are unset indices, those get filled with a default grayscale palette. If multiple shades in the image correspond to the same image, the palette is instead built as if the image had color. This slightly complex behavior is required for the expected behavior for images using Game Boy grayscale: if a PNG doesn't contain all four shades of gray, you'll most likely still want black to be 3 and white to be 0.
* Non-indexed PNGs with color (and those that failed the grayscale method) have their colors sorted from lightest to darkest.

If the palette has too few colors, it's padded with black. Transparent pixels are set to index 0, to make transparency usable for sprites.

I've tested this patch with pokecrystal and Telefang, and fairly exhaustively using the following PNG types:
* Grayscale
* Grayscale with alpha
* Grayscale with tRNS chunk
* Indexed
* Indexed with tRNS chunk
* RGB
* RGB with PLTE chunk
* RGB with tRNS chunk
* RGBA
* RGBA with PLTE chunk

As you may notice, I had to restructure `rgbgfx`'s code a bit. Before, everything was handled using libpng structs being passed around. Since analyzing the color of the pixels requires reading the image, that'd mean you'd need to read from the image, then edit it, and then read from it again – but reading from an image twice isn't possible in libpng. That means you'd need to read from the image, analyze the colors, write to a new dummy image struct, and then copy that to *another* image struct to get the final data. To prevent this, I moved all but the input/output logic to an intermediate representation (`RawIndexedImage`), which overall leads to improved efficiency and fewer workarounds.

I updated the man page for `rgbgfx` with details on how color is determined, but I didn't update the HTML documentation – I don't know which tool was used to convert the man page to HTML! If someone else can do it, that'd be sweet.

I also fixed a few miscellaneous bugs and inconsistencies I saw lying around. These fixes include:
* The `-x` option now calculates max trim based on the number of tiles in the image, as opposed to the width of the image in pixels.
* Only images with widths and heights of a multiple of 8 are allowed. Before, `rgbgfx` would simply ignore extra columns of pixels, and usually throw a memory corruption error when supplied with too many rows.
* Free memory that was allocated but never freed before.
* Changed inconsistent variable naming for image structs.
* Added missing includes here and there.

That's it! If you've got any questions or concerns, I'd be happy to answer them, of course.

### CODE REVIEW

**Comment by AntonioND** [comment]
First of all, thanks for this. I'll take a look at the code and give feedback, but it looks good.

However, I think you'll have to soften the restriction of the image size. Enforcing a multiple of 8 for the width is fine because of the format of the tiles, but for height it's causing problems in https://github.com/pret/pokecrystal, and I can see why someone would want to use a different size (you could have 2 half sprites in 2 different png files, for example, and put them together in the ROM).

```
error: Input PNG file gfx/mobile/up_arrow.png not sized correctly. The image's width and height must be multiples of 8.
error: Input PNG file gfx/mobile/down_arrow.png not sized correctly. The image's width and height must be multiples of 8.
```

I'm wondering if the palette can be provided as a command line option or as an input file, so that multiple sprites can share the palette.

**Comment by AntonioND** [comment]
And it would be great to be able to load tiles from an external file to share tilesets too, I don't know if that can be done right now...

I forgot to say it in the previous message, to generate the documentation you just have to do `make wwwman`.

Also, I've seen several coding style issues with the patch, could you use `make checkpatch` to correct them? It's explained here: https://github.com/rednex/rgbds/blob/master/CONTRIBUTING.rst#contributing-code I've just checked in my PC and there is at least one false positive, but try to fix as many as possible (specially the tabs vs spaces).

**Comment by obskyr** [comment]
Oh, sorry, I thought I'd read the contribution guide properly, but somehow I glossed over the code style tests! I'll fix that, of course. I'll add the HTML documentation too.

As for the height... at the moment, `rgbgfx` completely breaks when you have an image more than 1 tile wide with superfluous rows of pixels. Due to the way tiles are laid out in memory, superfluous rows for more than 1 tile doesn't really work – it'd mean holes in the output file. Should I change the validation to allow extra rows if the image is only 1 tile wide?

Regarding the palette command line option... I considered it. I can't quite come up with a use case, though. If you care about the exact palette, wouldn't you use indexed PNGs? Perhaps it'd be easier to keep track of a separate palette file or a command line option than what color type your PNGs are – is that a good reason to add it?

**Comment by AntonioND** [comment]
> Oh, sorry, I thought I'd read the contribution guide properly, but somehow I glossed over the code style tests – if I've accidentally mixed tabs and spaces, that's a crime I need to atone for (and apparently I didn't test pokecrystal after adding the validation... whoops)! I'll fix that, of course. I'll add the HTML documentation too. I'll also go ahead and rebase and sign the commits, because I hadn't done that either!

No problem.

> As for the height... at the moment, rgbgfx completely breaks when you have an image more than 1 tile wide with superfluous rows of pixels. Due to the way tiles are laid out in memory, superfluous rows for more than 1 tile doesn't really make sense – it'd mean holes in the output file. Should I change the validation to allow extra rows if the image is only 1 tile wide?

I can think of someone that might decide to compress a picture by just having 4 rows that are duplicated when they are loaded (like the "Game Boy" logo of the boot ROM). It is a bit of a weird use case, though.

As long as pokecrystal compiles, I'm happy. I guess that you can remove the restriction for 1 tile wide images if that makes it easier.

> Regarding the palette command line option... I considered it. I can't quite come up with a use case, though. If you care about the exact palette, wouldn't you use indexed PNGs? Perhaps it'd be easier to keep track of a separate palette file or a command line option than what color type your PNGs are – is that a good reason to add it?

Ok, good point, maybe we can ignore this for now until someone comes up with a good reason for it.

**Comment by obskyr** [comment]
>As long as pokecrystal compiles, I'm happy. I guess that you can remove the restriction for 1 tile wide images if that makes it easier.

It's not because it's easier – it's because there's no possible reasonable behavior for wider images with extra rows.

Pixels are stored a tile row at a time, right? First 8 pixels in a row, then the next 8 pixels get placed under those, and so on. Imagine a PNG of 3×2 tiles, if you will, and then one extra row of pixels at the bottom. The first row of tiles goes fine – 3 complete tiles. The second row also goes off without a hitch. Now for the extra row of pixels. The first 8 pixels go just fine – they're placed directly after the last tile's data. But... to continue with the next byte of 2bpp data, `rgbgfx` needs to go to the row *below* that one. The problem is, there isn't one. If there were no more tiles width-wise, that's fine, since `rgbgfx` can just stop there. But there's another tile to the right, so `rgbgfx` needs to continue! So what do you do with that run of unspecified bytes until the next tile? Pad those pixels with `0x00`, maybe? That's some weird opinionated behavior (how do we know what should be in that space?), and what's more, it's not useful since you can't put any data in between afterward.

So... that's why support for extra pixel rows for images wider than 1 tile doesn't make sense. If you come up with reasonable behavior for it, lemme know!

**Comment by obskyr** [comment]
Okay, so... I can't get `checkpatch.pl` to be happy with me. If I break up long function definitions like this:

```c
static void rgba_png_palette(struct PNGImage *img,
	png_color **palette_ptr_ptr, int *num_colors);
```

...It throws an error saying I need to align continuation lines to the opening parenthesis. But if I do that, like this:

```c
static void rgba_png_palette(struct PNGImage *img,
			     png_color **palette_ptr_ptr, int *num_colors);
```

...It throws an error saying I can't use spaces! What should I do about this?

**Comment by obskyr** [comment]
There we go! That should be all. Have a look at the code if you'd like; see if anything catches your eye.

**Comment by AntonioND** [comment]
I've fixed a couple of coding style issues and added the signed-off-by lines to the commit messages, I suppose you don't mind. The patches are now in the `develop` branch.

**Comment by AntonioND** [comment]
Also, because the patches aren't exactly the same, GitHub doesn't know that this has been merged, so I'll just close it manually.

**Comment by obskyr** [comment]
Well, it would've been nice to have fixed it myself (especially as GitHub doesn't count authored commits as contributions, only committed commits), but I guess what matters most is it made it into the repo.

What style issues did I leave behind?

**Comment by AntonioND** [comment]
As far as I know, it counts authored, not commited. But by default the contributor list only shows what there is in the master branch and it is not there yet. However, if you want, you can modify the patches and I'll force push tomorrow. As I said, they are not in the master branch so it doesn't really matter that much.

**Comment by AntonioND** [comment]
Regarding the issues, just diff the two branches, that should be enough.

**Comment by obskyr** [comment]
I think I'll take you up on that – mostly because having "obskyr authored" on a commit I didn't *really* author feels a bit uncomfortable (plus, the `Signed-off-by` line doesn't mean much if the commit isn't actually signed).

I did change a few minor things from your edits, just as a heads-up:
* Used my own phrasing for the commit messages again – "code style" is more common than "coding style", for example. I did, however, restrict the header lines to 50 characters and removed the mention of pokecrystal (as I understand if you don't want to mention it in the git history).
* That comma in that one comment *should* be there – it implies a sequence of events, as opposed to them happening independently. :grin:
* Changed the `setjmp` error message you added back to an `exit(1)`, as the error message you provided is incorrect. The program jumps there if libpng fails to parse the file (not if `setjmp()` fails to set up a jump buffer), in which case libpng prints is *own* message. As such, rgbgfx doesn't need to print anything there.

I've added the extra fixes to the `rgbfx-color` branch of my fork – you can reset the `develop` branch to `d602ebf` and then reopen this pull request and it'll all work out, I think.

**Comment by AntonioND** [comment]
I can't reopen this, unfortunately, I think you have to do it. In any case, I've just realized that you are adding pokecrystal as a submodule in the first patch, could you modify that commit and remove it? Also, could you squash the 2 commits that fix the code style and fix this? And wrap the comment of the first commit to 72 columns.
```
src/gfx/makepng.c:202: WARNING: line over 80 characters
+        * Transparent palette entries are removed, and the palette is collapsed.

src/gfx/makepng.c:483: ERROR: trailing whitespace
+^I$
```

**Comment by obskyr** [comment]
Oh yeah, absolutely, I must've `git add *`ed carelessly. Thought I had the
test folders in my `exclude`, but I guess not. I'll iron out those things
and open a new PR as soon as I have the chance.

**Pull request closed without merging**
