### PR TITLE
Report failing file names in comparisons

### PR DESCRIPTION
**Pull request by ISSOtm**
The files being diffed (especially for `.pipe` variants) are temp files, so their names are pretty nondescript. This improves error output, using ANSI escape sequences to make the lines stand out.

### CODE REVIEW

**Comment by ISSOtm** [comment]
I'm mostly unsure about portability of those escape sequences. Is this a good idea?

**Comment by ISSOtm** [comment]
GitHub seems to have missed the memo, but CI is full green.

**Comment by aaaaaa123456789** [comment]
This is portable as long as you're using a terminal that supports ANSI escape codes. Most of them do.

But for the odd time they don't, you might want to add a flag to the script to disable the escape sequences.

**Comment by AntonioND** [comment]
At this point I wonder if it's a good idea to rewrite the CI in not-bash.

**Comment by ISSOtm** [comment]
(Rebased onto current master to fix conflicts)

> At this point I wonder if it's a good idea to rewrite the CI in not-bash.

I don't know. What we currently have seems to work fine, and I'm not sure what benefits would be gained from using another scripting language. The script might be a little confusing, but [comments may help clarify](https://github.com/rednex/rgbds/blob/e7eac583daf97ff6eb69b7d6b36cb227fcee6876/test/link/test.sh)?

**Comment by AntonioND** [comment]
Well, I guess that the main problem is that there is no great alternative to a shell script in this case. This is just a bunch of glue code between different tools... But yeah, after taking a look at the script, I can't help but think of how messy the syntax of that language is.

**Comment by ISSOtm** [comment]
Can't help but agree, but we do need something that gets the job done, and something like a Python script seems heavy-handed. It's basically invoking programs and lightweight processing of text files, which is what the shell is good at.

**Comment by ISSOtm** [comment]
Fixed merge conflicts.

**Comment by NieDzejkob** [comment]
Using the `tput` command instead of raw escape will handle all terminals that could otherwise be problematic, and degrade gracefully.

**Comment by ISSOtm** [comment]
Handled in 44cdcd1.

**Pull request merged**
