### PR TITLE
Convert README to markdown

### PR DESCRIPTION
**Pull request by rogersachan**
I have converted the markdown of this project for convenience and added readability.

### CODE REVIEW

**Comment by AntonioND** [comment]
I was actually thinking about reStructuredText. GitHub-flavored markdown is quite inconsistent. I'd like to know more opinions about this, but I've switched to it in my current projects and intend to use it in my future ones.

**Comment by rogersachan** [comment]
@AntonioND I can always use Pandoc if that is really necessary, but seeing how simple the readme is at the moment I don't think we need rst.

Github limits rst formatting anyway.

**Comment by Ben10do** [comment]
I'm personally not familiar with reStructuredText, so I'm probably not going to be much help if we're going to discuss the two…

**Comment by AntonioND** [comment]
What I'm thinking is about migrating all the documentation to rest instead of having a really old html documentation that is... less than friendly to the eye: https://github.com/rednex/rednex.github.io

**Comment by rogersachan** [comment]
@AntonioND Check out readthedocs.org

**Comment by AntonioND** [comment]
I'm going to merge this because it's better than nothing, but I've created a new issue to discuss this: https://github.com/rednex/rgbds/issues/129

**Pull request merged**
