### PR TITLE
Improve section management

### LINKED ISSUE #274: RAM code and COPYSECTION
This is a proposed solution to #272, but it's different enough that I'm making a separate issue.

I've implemented something that makes RAM code easy before, for [swapdump](https://github.com/Sanqui/swapdump).

Basically, I implemented two new rgbds features:
* A `-r` option to rgbasm which lets you put code in RAM (https://github.com/Sanqui/rgbds/commit/4f7b98fd383064fe749b92321c62ac7f0cb098d8)
* A `COPYSECTION` directive which creates a binary copy of an already-written section (https://github.com/Sanqui/rgbds/commit/eac57476c1b5acf54cfb05c138412e4e72058825)

Usage then follows:

```
SECTION "ram code", WRAM0[$C000]

RAMCode:
    jp RAMCode
```

This will not emit any bytes, but the section will be compiled, the space will be reserved and the labels will be calculated (resulting in a proper `jp $C000`)

```
COPYSECTION "ram code", ROMX[$4000], BANK[$1]
```

This will take the section output as "ram code" and create a new section with exactly the same data.  Since the WRAM section would never have been output, this is the way to actually place the generated opcodes in ROM, to be copied to RAM later.

Now, I don't know if this approach is sensible and I haven't tested it extensively, but should you like it, I can rebase and make a pull request.

### LINKED ISSUE #471: Passing an out-of-bounds address to a section causes rgbasm to silently fail and then rgblink to segfault
When defining a section and requesting an address that is out-of-bounds, `rgbasm` finishes instantly without actually assembling the code, but does not show any errors and also creates an object file. When running `rgblink` on that object file, it segfaults. A minimal example is as simple as that:

```asm
SECTION "Oops", HRAM[$0]
    ds 1
```

you don't even have to add a header or anything else.

### PR DESCRIPTION
**Pull request by ISSOtm**
Closes #274 (almost two years old!) and fixes #471 for good.

This does a lot of cleanup regarding `SECTION`s, which should simplify future maintenance and reduce the amount of bugs.

### CODE REVIEW

**Comment by AntonioND** [comment]
Can you describe how to use the new keywords?

**Comment by ISSOtm** [comment]
Right, I forgot the man pages again.

**Comment by AntonioND** [comment]
Woops, you saw my message before I edited it. For now, just write here how to use it, the documentation can come later.

**Comment by ISSOtm** [comment]
Oh, right. I linked to [the description I made](https://github.com/rednex/rgbds/issues/274#issuecomment-579464703) in a previous draft of the PR message, but I deleted it ^^'

**Comment by ISSOtm** [comment]
I just added a section to RGBASM(5) that describes this. Is it understandable?

**Comment by AntonioND** [comment]
It looks reasonable to me.

**Pull request merged**
