### PR TITLE
Add checks to most libc functions

### PR DESCRIPTION
**Pull request by AntonioND**
File I/O functions and dynamic memory functions can fail, they return error codes, but pretty much nowhere in the codebase they are actually checked.

I've implemented a wrapper around the libc functions that make the toolchain programs exit gracefully in case of an error. They also report the name of the file and the line inside the file that caused the error.

This system allows the code to be cleaner because of not having so many checks everywhere.

Fixes https://github.com/rednex/rgbds/issues/204

### CODE REVIEW

**Comment by bentley** [comment]
I’m not a fan of this style of coding. Wrapping every libc function is unidiomatic and doesn’t buy us much in terms of useful error reporting.

Certainly for stdio functions, I would rather take [the approach suggested by Rich Felker](https://stackoverflow.com/questions/7462428/c-fputc-error-handling#7462547) of simply checking ferror() before closing the file, then erroring from there.

I’m more sympathetic when it comes to memory allocation. But if we’re avoiding the standard functions, I’d rather implement a single function that handles new allocations, reallocations, and avoids multiplication overflows: like [https://man.openbsd.org/reallocarray.3](reallocarray()], but with built‐in exit‐on‐error.

free() doesn’t need any wrapper, as it cannot fail. The standard explicitly states that free(NULL) has no effect, so there’s no need to even check the argument.

**Comment by bentley** [comment]
Null checks can’t detect a double free.

I don’t agree that free(NULL) is bad style either. Unnecessary checks are—if a null is a problem at all then the problem really lies with a failed allocation or wrong assignment. If that’s the case then !null assertions would be a better option.

reallocarray() isn’t complicated—it’s just realloc() with an overflow check. Neither one frees memory (except when resizing to a bigger object).

There are only a handful of file reads in RGBDS: one in the lexer, three in the object parser, two in overlays. That’s few enough that idiomatic C error checks are manageable, IMO.

I’m also open to the idea of modify the code to reduce the need for error checks. For example, rgbfix could modify a copy of the header in memory rather than performing a ton of file reads and writes throughout.

**Comment by AntonioND** [comment]
Yes, they can. Let's say that a child function calls `AllocateObject()` and then the parent function, because of a bug. A memory leak occurs when the pointers are assigned a new value returned by `malloc`. Then, a different child function calls `free` and sets the pointer to `NULL`, and the parent folder calls `free` again on a `NULL` pointer. There is no crash, so you can't tell if there is a memory leak.

Of course, this is a very specific example, but that's why I thought about the wrappers I've proposed, Adding a sanity check is as simple as adding 'z' in front of 'free'. The same argument you have made could be used to discourage the use of `assert()` in debug code. After all, they are made to check conditions that are not meant to happen.

`realloc(ptr, 0)` is often misused as a `free` because in some implementations it works that way. Using a function that has an undefined behaviour in a simple case like this is a bad idea. I'm specially concerned about it because just a few weeks ago we had this problem with a piece of code that did `malloc(0)`: https://github.com/rednex/rgbds/issues/252

There are several `fgetc` in `rgblink`.

However, I do agree that maybe the best thing to do is to simply read the file to a buffer and read data from there.

**Comment by bentley** [comment]
> Yes, they can.

No, they can’t. Freeing a pointer doesn’t set it to NULL. That means that double frees can’t be detected in the way you describe (or indeed at all, at least not by the program, without manual bookkeeping).

> There is no crash, so you can't tell if there is a memory leak.

But it does crash!

    a.out(10929) in free(): chunk canary corrupted 0x800d2f51230 0x1@0x1 (double free?)

Even on Linux:

    *** Error in `./a.out': double free or corruption (fasttop): 0x000000000187e010 ***

It can also be detected by static analysis:

    $ scan-build make
    scan-build: Using '/usr/local/bin/clang-5.0' for static analysis
    /usr/local/bin/../libexec/ccc-analyzer -O2 -pipe    -o foo foo.c 
    foo.c:8:2: warning: Attempt to free released memory
            free(x);
            ^~~~~~~
    1 warning generated.
    scan-build: 1 bug found.

There are already tools to find these sorts of bugs. Manually setting a freed pointer to NULL (which I don’t think you’ve suggested) would *hide* the bug in all the diagnostics shown above.

> The same argument you have made could be used to discourage the use of `assert()` in debug code. After all, they are made to check conditions that are not meant to happen.

The difference is that assert() is idiomatic C, and wrapper macros are not. Someone familiar with the standard library or who refers to documentation knows exactly what free() and assert() do; to understand zfree() means reading through the source code (first the header, then the C file).

> realloc(ptr, 0) is often misused as a free because in some implementations it works that way.

So it does. My mistake (but it’s in the standard, so I wouldn’t call it misuse).

> I'm specially concerned about it because just a few weeks ago we had this problem with a piece of code that did `malloc(0)`: #252 Trying to allocate 0 bytes of memory is common enough for this to be a problem, in my opinion.

Okay, but your macro wouldn’t have noticed that either. malloc(0) can’t be detected by the return value; you have to check the input beforehand.

I do think that given the number of unchecked mallocs in RGBDS, a single allocation function wrapper would make sense. One that:

* takes two arguments like calloc()/reallocarray(), preventing multiplication overflow
* prohibits zero‐size arguments (thus leaving frees solely to free())
* simply exits on error (this would be unacceptable in a library, but good enough here)

If we’re adding nonstandard wrapper macros I would prefer just one that both allocates and reallocates, but I wouldn’t mind two. We don’t need calloc’s clearing behavior though (I think?), so three would be too many.

> There are several `fgetc` in `rgblink`.

Sorry, I meant to mention those too. I think a wrapper around fgetc() makes sense there, because 1) it could be defined in the sole file where it’s used (object.c) and 2) a readbyte() function would match well with the readlong() already present in the same.

**Comment by AntonioND** [comment]
The double free crashes are an implementation-defined behaviour. However, if you make the pointers NULL after free, and then check whenever you are going to free, that works everywhere.

> So it does. My mistake (but it’s in the standard, so I wouldn’t call it misuse).

The standard says the behaviour is implementation defined, relying on it being a free makes the code not portable. This makes the function quite broken in my opinion. It's the same issue as trusting signed integers to use two's complement. They are in 99.9% of cases, but the standard doesn't mandate it, so the compiler will do bad things to code that assumes they are. In case someone is wondering what I'm talking about: `int fn(int a) { return a + 2 > a; }` always returns 1 because the overflow is undefined so the compiler is free to return anything in that case, and it's easier to just return 1 all the time.

-----

In any case, I would have a function for malloc, realloc and free. I think it's clearer that way.

And yeah, probably a readbyte makes sense there. However, I think the real solution would be to load the full files whenever possible and do any error checking there. Then, modify the readlong and readabyte functions (or whatever) to read from RAM instead of using I/O functions.

**Pull request closed without merging**
