### PR TITLE
Clarify install instructions on Windows

### PR DESCRIPTION
**Pull request by clach04**
Add Windows path note, in preference from adding exes to system locations

### CODE REVIEW

**Comment by clach04** [comment]
> I don't remember that `path` command. Is it new to Windows 10?

No, its from old MSDOS, I would have guessed from the initial version, definitely present in MS-DOS 3.x from the late 80's. The alternative is to use the SET command, similar to unix shell.

**Comment by ISSOtm** [comment]
Okay then.

**Comment by NieDzejkob** [comment]
The version is still mentioned in the directory name. Is that intended?

Also, does this command make the changes persist, or will the new PATH not apply anymore when the commandline is closed?

**Comment by clach04** [comment]
> Also, does this command make the changes persist, or will the new PATH not apply anymore when the commandline is closed?

Does not persist, will not apply once CMD is exited. Only way to persist is to set in system settings (via GUI admin tools see https://www.java.com/en/download/help/path.xml)

**Pull request merged**
