### PR TITLE
Allow test repos to be kept locally

### PR DESCRIPTION
**Pull request by Ben10do**
*(I thought I submitted this PR a few days ago…)*

We no longer assume that the test repos don’t exist when we run `run-tests.sh`. This allows developers to choose to keep them, to allow them to run the tests more quickly.

- Add the test repos to the .gitignore.
- Check if the directory for each repo already exists, before trying to clone it.
- Do a `git pull` for each repo, to ensure that existing copies of repos are up-to-date.

### CODE REVIEW

**Comment by AntonioND** [comment]
Thanks for this! It can be useful for doing local tests.

However, an idea I had some time ago is to only test the last tagged release of each of the repositories we test. That way, even if the repository is temporarily broken, we wouldn't notice. However, that also means that we need to update the versions used in the test script whenever there is a new release. And there's also the problem of pokered and pokecrystal not having actual releases, we would need to use specific commit hashes. What do you think?

**Comment by Ben10do** [comment]
Sounds sensible to me. I did actually have to open a PR in pokecrystal to get that to build on my Mac, so hopefully this would make that a less common occurance.

While it’d be more to maintain, I think it would be worth it just to ensure that our builds don’t get broken for us.

I also don’t see any problems with using specific commits in the absence of tags.

Do you want me to do this as part of this PR? If so, would you prefer me to do so with an extra commit?

**Comment by AntonioND** [comment]
Then let's use specific commits.

Yes, add a patch on top of the current one.

Thanks.

**Comment by Ben10do** [comment]
OK, that should be sorted now! Hope this implementation looks sensible to you.

From a selfish perspective (because, for better or for worse, I use spaces in my filesystem), it'd be nice if you could merge AntonioND/ucity#1 before this gets merged. If so, I'll amend that last commit. It's not the end of the world if that doesn't happen, though 🙃

**Comment by AntonioND** [comment]
Well, I've just merged the PR, so you will have to change the reference for that repository. Otherwise, it looks good.

**Comment by Ben10do** [comment]
Thanks! That should be all sorted now 😃

**Comment by AntonioND** [comment]
And merged.

**Comment by AntonioND** [comment]
Also, I've re-enabled OS X builds in Travis CI: https://github.com/rednex/rgbds/commit/34e04b0327377ba988e1a7d38a1d699cb03e12f2

**Comment by AntonioND** [comment]
And it's broken because it's missing md5sum, perfect...

**Comment by Ben10do** [comment]
That works, sorry I missed that build break…

For pokecrystal, they started using their own tool written in C for calculating MD5 checksums, likely since I reported that `md5sum` isn't installed by default. While investigating that, I must've installed `md5sum` on my machine to see what it was supposed to do, exactly, which remained on my machine up to now, so I missed the same problem with pokered…

I'll see if I can get them to use the same tool for pokered, so we don't have to install more than we need!

**Comment by Ben10do** [comment]
One more thing; since GCC on the Mac is just an alias for Clang by default, we probably don't need both GCC and Clang builds on Travis – it'll just be doing the same build twice.

So, I think we should be able to disable GCC builds by adding:
```yaml
matrix:
  exclude:
  - os: osx
    compiler: gcc
```

I'd have piped up about this earlier, but I wasn't ready for you to just go ahead and re-enable Mac builds like that 😉

**Comment by AntonioND** [comment]
Well, I didn't expect to need anything else apart from enabling it... :P

If you want to improve the Mac builds, go ahead. I have no idea of how things are done there. If you think this is something we should do, create a patch. Maybe there's something else we could do to optimize Mac builds.

**Comment by AntonioND** [comment]
Oh, I didn't see the previous message. Yeah, it would be nice if they could move away from md5sum, but it's no big deal, the workaround is easy enough.

**Pull request merged**
