### PR TITLE
Fix memory errors in makepng

### PR DESCRIPTION
**Pull request by JL2210**
This includes not checking the result of `malloc` and
using the wrong type in `sizeof`. Only the latter was
caught by `scan-build`.

Signed-off-by: JL2210 <larrowe.semaj11@gmail.com>

### CODE REVIEW

**Comment by ISSOtm** [comment]
For `sizeof`, we prefer using `T *ptr = malloc(sizeof(*ptr));` rather than `T *ptr = malloc(sizeof(T));` ([rationale](https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst#14-allocating-memory).)

There are a lot of places where this should be changed, but if you don't want to bother, I'll do it myself... though RGBGFX deserves an overhaul too.

**Comment by JL2210** [comment]
I was hoping that was the case. I prefer the former, too.

**Comment by JL2210** [comment]
After some checkpatch issues, should be done if no objections.

**Comment by ISSOtm** [comment]
Great! LGTM, merging.

**Pull request merged**
