### PR TITLE
test/asm: Generate .out.pipe files on the fly

### PR DESCRIPTION
**Pull request by NieDzejkob**

### CODE REVIEW

**Comment by NieDzejkob** [comment]
Force-pushed to split the commits, making GitHub's diff easier to read.

**Comment by NieDzejkob** [comment]
Force-pushed to change the shell to bash, since the `dash` used on some distros doesn't support this kind of substitution.

**Comment by NieDzejkob** [comment]
cc @AntonioND - was it you who uses FreeBSD? Does FreeBSD use `bash`? Is it reasonable to require `bash` for building? (Debian and Ubuntu use `dash` by default, which breaks when testing this PR)

**Comment by AntonioND** [comment]
> cc @AntonioND - was it you who uses FreeBSD? Does FreeBSD use `bash`? Is it reasonable to require `bash` for building? (Debian and Ubuntu use `dash` by default, which breaks when testing this PR)

That's @bentley, but I advise you to create a VM to test with. I have OpenBSD, FreeBSD and Fedora and sometimes use them for tests. Bash is probably reasonable.

**Comment by bentley** [comment]
bash is not a reasonable requirement. Neither is assuming it’s at `/bin/bash`.

POSIX sh, please.

**Comment by NieDzejkob** [comment]
On Thu, Aug 29, 2019 at 09:15:41PM -0700, Anthony J. Bentley wrote:
> POSIX sh, please.

Okay, what's a good portable way to replace $a with $b without
$a being interpreted as a regex? This is the best I've got so far.

**Comment by bentley** [comment]
Escape the separator (`/`), the escape character (`\`), and regex metacharacters, then use sed.

```diff
 			# that's harder to deal with and was broken when the feature was
 			# first implemented.
 			cat $i | ../../rgbasm -o $o - > $after 2>&1
+			subst=$(printf '%s\n' "$i" | sed 's:[][\/.^$*]:\\&:g')
 
-			# A filename is not a regex, so sed can't be used here.
 			desired_output=$before
 			> $desired_output # Remove any previous contents
 			while IFS= read -r line; do
-				echo "${line//$i/-}"
+				echo "$line" | sed "s/${subst}/-/"
 			done > $desired_output < ${i%.asm}.out
 		fi
 
```

Ugly, but portable.

**Comment by NieDzejkob** [comment]
Two force-pushes occured:
 - applied @bentley's suggestions, factoring out the innermost loop, as it was only used to work around sh's newline handling
 - rebased onto master

**Comment by ISSOtm** [comment]
Considering the only changes requested have been applied and CI passes, I'm counting this as approved.

**Pull request merged**
