### PR TITLE
Fix out of bounds array access in lexer

### PR DESCRIPTION
**Pull request by dbrotz**
If the type `char` is signed, then in the function `yylex_GetFloatMaskAndFloatLen()`, `*s` can have a negative value and be converted to a negative `int32_t` which is then used as an array index. It should be converted to `uint8_t` instead to ensure that the value is in the bounds of the `tFloatingFirstChar`, `tFloatingSecondChar`, and `tFloatingChars` arrays.

### CODE REVIEW

**Comment by AntonioND** [comment]
https://travis-ci.org/rednex/rgbds/builds/544384725

**Comment by AntonioND** [comment]
I think that all the information you've written in the PR should be in the commit message as well.

**Comment by dbrotz** [comment]
I've added a commit to fix #367 because it's closely related and it required modifying a test I added in this PR.

**Comment by dbrotz** [comment]
I've fixed #326 as well now. I put it here because I realized that I would have to move the code to skip the UTF-8 BOM in order to properly detect a `*` on the first line.

**Comment by AntonioND** [comment]
After merging another PR there are conflicts on this one. Could you fix them?

**Comment by dbrotz** [comment]
I've fixed the conflicts.

**Pull request merged**
