### PR TITLE
Print location information in linker errors where viable

### PR DESCRIPTION
**Pull request by NieDzejkob**
"Requested BANK() of unknown section" and "Unknown symbol" now print the file and line.

### CODE REVIEW

**Comment by AntonioND** [comment]
Looks good to me. Why isn't travis working? Strange...

**Comment by AntonioND** [comment]
https://travis-ci.org/rednex/rgbds/builds/501231874

**Comment by NieDzejkob** [comment]
Travis looks okay to me...

**Comment by AntonioND** [comment]
Well, there is no green tick or red cross next to your commit. However, as soon as I merged the other PR it ran the tests and now the tick appears in the list of commits. It's weird.

**Pull request merged**
