### PR TITLE
Assume dmg-style WRAM0 sections if no WRAMX sections are used.

### PR DESCRIPTION
**Pull request by yenatch**
Implements #52.

### CODE REVIEW

**Comment by bentley** [comment]
I don’t really like this behavior. Clueless newbie has a big WRAM0, then runs out of space so creates a WRAMX. Suddenly WRAM0 spews “section full” errors.

**Comment by yenatch** [comment]
Could the error mention that as a possible cause?

Having thought on it, a better solution would be a new keyword. WRAM is free to use. Would people confuse it with WRAM0/X?

**Comment by bentley** [comment]
Interesting idea. If that were implemented then there could also be a ROM keyword, like ROM0/ROMX but $8000 bytes, that obviates `rgblink -t`.

**Comment by AntonioND** [comment]
I prefer this implementation: https://github.com/rednex/rgbds/pull/122

**Pull request closed without merging**
