### PR TITLE
Add support for OAM Sections

### LINKED ISSUE #72: A section for OAM RAM
In WLA-DX I can have an enumeration where OAM RAM is defined ($FE00). RGBDS doesn't appear to have enums or a section that can reach that point. Can there be one?

### PR DESCRIPTION
**Pull request by Ben10do**
This allows sections (and labels within) to be defined that correspond to the Game Boy’s Object Attributes Memory.

It can be used in a similar manner to any other section type: `SECTION "My OAM Section", OAM`. Of course, OAM sections may also be fixed or aligned as desired.

Also, as part of this change:
- The object file version has also been bumped to v4 in order to accommodate the new section type.
- Some magic numbers have been replaced with `BANK_COUNT_*` constants, particularly in `src/link/patch.c`.
    - As a side effect, this could fix a theoretical bug when using `BANK(Label)` when `label` is in a high SRAM bank (≥ 4).

As always, feel free to do additional testing, and make changes as necessary. Fixes #72.

### CODE REVIEW

**Comment by AntonioND** [comment]
Could you split this into 2 commits? To make it easier to bisect for problems. Also, you should probably place the OAM sections after WRAMX or HRAM, not after SRAM.

I think the idea of OAM sections is pretty useless, but the reorganization is fine, so... Maybe for small games it is useful...

**Comment by Ben10do** [comment]
Sure, how would you like me to split the changes? 

I'm happy to move the OAM sections before SRAM – I assume by that you mean the order as in `eBankDefine` (so I'd move `BANK_OAM`). It won't be possible to change the order of the section types (e.g. `SECT_OAM`) without breaking backward compatibility (#132).

Yeah, I agree, seeing as DMA is the preferred method of accessing OAM, but I suppose that there's no harm in adding this for users who do want it.

**Comment by AntonioND** [comment]
First reorganize the bank indexes and such, then add the OAM sections.

I don't really think backwards compatibility is a problem. If we need to add more SRAM banks in the future that will certainly be a compatibility break anyway.

**Comment by Ben10do** [comment]
OK, that should be sorted!

**Pull request merged**
