### PR TITLE
Improve 'charmap' structure for a better performance

### PR DESCRIPTION
**Pull request by jidoc01**
I editted previous charmap structure to the new one which was based on string process data structure.
With this new one, you can feel the dynamic improvement in speed, especially when you have a lot of nodes in charmap.

I also fixed some part of 'asmy.y', which caused some situations with problem in UTF-8(I've experienced it in my poketcg after changing my rgbds to the newest version).

It's my first pull-request, so please tell me anything I need to fix up. Thank you.

* And I forgot to say an important thing! In this modification, you can use multiple characters in charmap's output side. For example, you can define like:
charmap "1", "One"
charmap "2", "Two"
And for performance stability, I restricted it only below 4 characters.

### CODE REVIEW

**Comment by mid-kid** [comment]
Wait, in your example of `charmap "1", "One"`, what will the raw value of the output be? Is it just ASCII `One`, or is that parsed again with the charmap to get the charmap values for each individual character?
If so, would it be possible to specify raw values instead? As in, something like `charmap "1", $23, $24, $25`? I'm scared that would make something like https://github.com/rednex/rgbds/issues/265 impossible, however.

**Comment by jidoc01** [comment]
> 
> 
> Wait, in your example of `charmap "1", "One"`, what will the raw value of the output be? Is it just ASCII `One`, or is that parsed again with the charmap to get the charmap values for each individual character?
> If so, would it be possible to specify raw values instead? As in, something like `charmap "1", $23, $24, $25`? I'm scared that would make something like #265 impossible, however.

Oh, it seems right. As you mentioned it parses itself recursively, and I'm sorry I missed that point. I think that 'multiple characters in output' should be removed for its confusion, but it was an additional feature which I thought good to add up.

Actually, I commited mainly the improved efficiency in parsing. I want you to look up those parts.
Compared to the previous parsing method, now the count of nodes in charmap doesn't affect its performance. And there is no need to compare a given substring with a node with all length. I think, though there are only a few such games in gb/gbc, it would be helpful when many characters are involved, like kanji games.

**Comment by AntonioND** [comment]
There are several checkpatch errors in this code. Also, you should be using ``/* */`` style comments, not `//`.

**Comment by AntonioND** [comment]
Also, you need to rebase this on the current master and fix the conflicts.

**Comment by jidoc01** [comment]
> Also, you need to rebase this on the current master and fix the conflicts.

I guess those conflicts emerged because my commit's been a while? I'm gonna edit and commit it again as soon as I've got some free time. I am so busy these days, tho. Thanks for your advice. 
* For someone interested in this structure, it uses 'trie' for string processing.

**Comment by AntonioND** [comment]
I merged another PR before yours, so yeah, that's probably what caused the conflicts. It doesn't seem to be complicated to fix, there is just a block of code that needs your attention.

**Comment by jidoc01** [comment]
> I merged another PR before yours, so yeah, that's probably what caused the conflicts. It doesn't seem to be complicated to fix, there is just a block of code that needs your attention.

Hi. I modified the codes. Now I've finished it, and want to pull it newly. I wonder if I should close this pull-request and pull it as a new one. Sorry to bother you, cuz I'm a newbie. T_T

**Pull request closed without merging**
