### PR TITLE
Deprecate IMPORT, EXPORT and GLOBAL keywords

### PR DESCRIPTION
**Pull request by AntonioND**
Deprecated the following keywords:

- IMPORT is simply useless, any symbol that isn't found in the current
  file is automatically flagged as imported symbol.

- EXPORT could be useful if a label is defined as `label:` instead of
  `label::`, but the second version is preferred as it is less verbose.

- GLOBAL imports a symbol if it isn't found in the current file and
  exports it if it is found. Both comments above apply in this case.

### CODE REVIEW

**Comment by AntonioND** [comment]
As far as I know, some people use IMPORT as a way to make it explicit in the code. I don't know if this is something we want to allow or not. The keyword has been completely useless for a long time, it's basically a comment.

**Comment by l0k1** [comment]
I use `EXPORT` rather than `label::` quite a bit in my code, so I'm personally not a fan of depreciating it.

**Comment by AntonioND** [comment]
But why? I checked your comments in https://github.com/rednex/rgbds/issues/76 and you essentially use EXPORT as a comment to remind yourself that you are exporting that symbol. But I could say that it makes it less clear when you are checking the rest of the file as you have to go to the top of the file again to see which things you are exporting.

The ':' and '::' thing are clearer, I think.

I'm going to push the other patches and deprecate IMPORT, I'd like to know what others think about it. And, anyway, it's not going to stop working, it's just going to output a warning that can be silenced.

**Comment by l0k1** [comment]
> But why?

Because it's clearer for me, and it's how I like to organize it. Which is clearer, `EXPORT` or `label::`, is subjective IMO. But if it still works and just issues a warning that can be squelched, I'm fine with it.

Also, I agree that `IMPORT` is useless.

**Comment by AntonioND** [comment]
I'm going to close it,  I've just deprecated IMPORT, that should be enough.

**Pull request closed without merging**
