### PR TITLE
Improve dependency generation

### PR DESCRIPTION
**Pull request by ISSOtm**
This PR implements `-MG`, `-MP`, `-MT` and `-MQ` options, mimicking GCC's. See `gcc(1)` or the commit descriptions for what they do.

These options are useful for automatic dependency generation, and I have written a Makefile using them that incrementally generates an ASM file's deps by repeatedly assembling it. This would cause large projects to have a very slow initial build, but this is intended as an option for cases where the overhead is acceptable.

Due to #306's discussion, I have implemented these as short options through special-casing some arguments; they could be implemented more cleanly using `getopt_long_only`, I believe. I decided to use this implementation for the following reasons:
- POSIX-compilant;
- This is not backwards-compatible (if someone had their dep file called `Q` then this will break their workflow), but I don't think this will actually affect anyone;
- It does not consume additional letters for short options.

If this PR gets approved, I will write corresponding entries into the man pages, but I don't want to have to do that and keep it up with changes I would have to make.

### CODE REVIEW

**Comment by aaaaaa123456789** [comment]
There's not much of a concern about someone having their dep file called `Q` (after all, they can still get the old behavior by doing `-M ./Q`); it's more about semantics. Long options should behave like long options; this is a completely unnecessary hack.

At some point you're going to run out of letters. Please stop this "long options are evil!!!!" stuff and just handle them in _some_ way.

**Comment by ISSOtm** [comment]
Needs fixing:
- Full path names (via `-i`) aren't output, only the partial path
- A .o file is still generated if `-MG` aborts compilation (see #446)

**Comment by ISSOtm** [comment]
I consider this blocked until #447 gets resolved (one way or another)

**Comment by ISSOtm** [comment]
Since #447 has been accepted, I will redo this using long options. Should I just make a new commit, or patch all existing ones?

**Comment by aaaaaa123456789** [comment]
I'd say make a new commit on top.

**Comment by ISSOtm** [comment]
I did that and also fixed a couple bugs I noticed through more testing.

**Comment by ISSOtm** [comment]
The two errors mentioned above have been fixed, at least I believe.

**Pull request merged**
