### PR TITLE
Allow overriding CHECKPATCH variable as described in CONTRIBUTING.rst

### PR DESCRIPTION
**Pull request by qguv**
Split from #346 at maintainer's request.

### CODE REVIEW

**Comment by AntonioND** [comment]
So I have doubts regarding this. If this is needed for ``CHECKPATCH``, it is also needed for the rest of the variables in the makefile, such as ``YACC``. How do you invoke ``make checkpatch``?

**Comment by qguv** [comment]
Without this patch, you can't run e.g.

    CHECKPATCH=/usr/src/linux/scripts/checkpatch.pl make checkpatch

because the CHECKPATCH variable will be overridden with the `:=`. You can use `?=` instead to allow the variables to be overridden by environment variables, see the [relevant section of GNU Make documentation](https://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_6.html#SEC64).

**Comment by AntonioND** [comment]
Sure, but then you need to apply this change to every variable in the makefile, such as ``Q``. And you can still do ``make checkpatch CHECKPATCH=/usr/src/linux/scripts/checkpatch.pl`` and it should work.

Either this change is applied to everything that needs it or it shouldn't be applied at all.

**Comment by qguv** [comment]
In that case, let's not fiddle with the Makefile and instead update CONTRIBUTING.rst to use the syntax with the variable name _after_ the make invocation:

> [...] By default, the Makefile expects the script (and associate files) to be located in ``../linux/scripts/``, but you can place them anywhere you like as long as you specify it when executing the command: ``CHECKPATCH=../path/to/folder make checkpatch``.

If you're okay with that, I'll close this and open another for CONTRIBUTING.rst.

**Comment by AntonioND** [comment]
Yeah, that sounds good to me.

**Pull request closed without merging**
