### PR TITLE
Add support for including files in linkerscript

### PR DESCRIPTION
**Pull request by AntonioND**
Files can now be included with the following syntax:

    INCLUDE "path.link"

The maximum include depth is 5.

Man page updated.

Fixes https://github.com/rednex/rgbds/issues/147

### CODE REVIEW

**Comment by Ben10do** [comment]
Any particular reason why you chose a maximum depth of 5? It sounds a little low to me… I'd personally go with more like 16 myself.

Also, it could quite easily be possible to dynamically allocate the includes stack, which would allow for as many includes as you'd like (although you'd have to be careful of infinite recursion, of course).

**Comment by AntonioND** [comment]
5 levels of depth seems like a lot more than people will use... I really don't expect anybody to use more than 3.

**Comment by Ben10do** [comment]
Sure, but it still feels like a rather arbitrary limitation, and I'd don't think that exceeding this limit is outside the realms of possibility.

**Comment by AntonioND** [comment]
Supposing each file of level 5 defines sections for 10 banks and each level includes 10 files of the following level, the result is 10^5 banks. Not even the disassemblies of Pokemon Crystal or similar need such a high depth, at most they need 2 more levels than the base file.

Of course, if someone finds this is too restrictive the define can be changed and that's it, but I can't think of a case in which making this bigger makes actual sense.

**Comment by AntonioND** [comment]
This should do it. I've also increased the number to 8, and that's a lot more than anyone could need.

**Pull request merged**
