### PR TITLE
Improve Makefile

### PR DESCRIPTION
**Pull request by ISSOtm**
This is a collection of commits intended to improve the Makefile; each being very small, I felt making a separate PR for each was going to be tedious for everyone involved.

### CODE REVIEW

**Comment by AntonioND** [comment]
Won't this break the build with BSD make?

**Comment by ISSOtm** [comment]
Which change would break it?

**Comment by ISSOtm** [comment]
CI fails with [this command](https://travis-ci.org/rednex/rgbds/jobs/581264795#L224) failing to link with the math library; however even with the the gcc 5.4.1 I have on my machine, I'm failing to replicate the build error... could it be a problem with the order of arguments?

**Comment by ISSOtm** [comment]
Fixed incorrect assumption about how `pkg-config` worked that caused the macOS CI builds to fail, but I still don't understand why the Linux GCC build fails.

**Comment by AntonioND** [comment]
Well, suffix rules don't work (``%.o: %.c``), as far as I know. That's why the Makefile is the way it is, it took me a while to get it working in BSD, and I don't see why we should break something that is already working.

Also, I think you should install a BSD VM to test build system changes. I can't test your changes right now because VirtualBox has decided to not work today, but probably @bentley can.

**Comment by bentley** [comment]
Yes, POSIX doesn’t specify metarules (`%` rules) and BSD make doesn’t implement them.

**Comment by ISSOtm** [comment]
According to the documentation, `${}` isn't specified by POSIX either, yet the Makefile uses them wildly. What gives?

**Comment by bentley** [comment]
POSIX does specify `${}`: it behaves exactly the same as `$()`.

**Comment by ISSOtm** [comment]
If so, then the behavior is different on GNU Make, and `$()` should be used instead, at least.

**Comment by bentley** [comment]
Different? How? I would be very surprised if GNU Make treated `${}` and `$()` differently in any way. Certainly it doesn’t differ in its treatment of macro expansions, the only thing RGBDS uses `${}` for.

**Comment by ISSOtm** [comment]
I misread the documentation, my bad.

**Comment by ISSOtm** [comment]
@bentley I have updated the PR to build on FreeBSD as well; is it better now?

**Comment by ISSOtm** [comment]
I would like to use `$^` in the binary file rules to eliminate some redundancy, and shim it with `^ = $(.ALLSRC)` on BSD Make, but I don't know how to detect and shim, except by creating an additional `GNUMakefile`.

**Comment by bentley** [comment]
I’m fine with the current commits (up to 1288737c0d195243b63fcbdd4c3b9a8ba3ce21ce), and they successfully build on OpenBSD.

I’d rather stick to POSIX than introduce BSD extensions. What redundancy are you trying to eliminate?

**Comment by ISSOtm** [comment]
My goal was to rewrite rgblink, so I wanted to:
- Replace references to `$(rgb%_obj)` in rules woth `$^`
- Simplify the object lists as much as possible
- Maybe also unify the rules, as this lended itself well to pattern rules

**Pull request merged**
