### PR TITLE
Implement unionized sections

### LINKED ISSUE #407: [Feature proposal] Cross-file `UNION`s
# Purpose

Some people program their code with a [single file](https://github.com/ISSOtm/Aevilia-GB/blob/master/main/wram.asm) that holds all memory declarations.

Others prefer [declaring variables next to where they're used](https://github.com/AntonioND/ucity/search?q=WRAM0&unscoped_q=WRAM0), but that prevents the use of `UNION`. For instance, @pinobatch's programming style is to have a buffer in HRAM that routines can use as scratch space; he currently works around it as explained [here](https://github.com/pinobatch/240p-test-mini/blob/master/gameboy/src/global.inc#L25-L70). Notable issues include the buffer size being fixed.

The purpose of this proposal is to present an `UNION`-like construct that can satisfy the latter programming style.

# Proposal

Things boil down the the creation (and handling) of a new type of `SECTION`. Here's an example declaration:
```
SECTUNION "Scratch space", HRAM,ALIGN[4]
```

A `SECTUNION` is treated like a `SECTION`, except that it can be defined several times in the same translation unit (= assembler invocation) and in several object files. Just like regular `SECTION`s, `SECTUNIONS` are identified by their name and memory type; this means that `SECTUNION "Scratch space", WRAM0` isn't the same as the one defined above.

Of course, by their very nature as `UNION`s, `SECTUNION`s will only be allowed for RAM.

When a second definition is encountered, the resulting `SECTUNION` tries to satisfy both constraints. The first four definitions below don't conflict, but the fifth one does:
```
SECTUNION "Scratch space", WRAM0,ALIGN[8]
SECTUNION "Scratch space", WRAM0,ALIGN[5] ; OK: alignment never conflicts
; The resulting SECTUNION is considered ALIGN[8]
SECTUNION "Scratch space", WRAM0[$CE00] ; OK: fixed address satisfies alignment
; The resulting SECTUNION is simply placed at $CE00
SECTUNION "Scratch space", WRAM0,ALIGN[9] ; OK: fixed address satisfies alignment
SECTUNION "Scratch space", WRAM0[$CE00] ; OK: fixed address matches

SECTUNION "Scratch space", WRAM0[$C000] ; Conflict: fixed address doesn't match
```
All symbols defined in a `SECTUNION` are implicitly part of an `UNION` that starts at the `SECTUNION`'s base.

Only one instance of a `SECTUNION` shall be output per object file, the assembler shall do as much merging as it can so as to speed up linking. The linker will merge all instances of a given `SECTUNION` using the same algorithm for each `SECTUNION` before any linking takes place, and generate internal `SECTION`s for each `SECTUNION`. The rest of the linking process will not be affected.

### PR DESCRIPTION
**Pull request by ISSOtm**
Fixes #407.

Documentation on the syntax has not been written in this PR because it would be problematic to write without the changes in #494. It will be added after #494 gets merged.
Until then, syntax examples can be found in the test files.

### CODE REVIEW

**Comment by aaaaaa123456789** [comment]
I'd recommend adding a few more tested for invalid situations.

1) Conflicting section types:

```
SECTION UNION "test", WRAM0
  db
SECTION UNION "test", HRAM
  db
```

2) Conflicting placement parameters:

```
SECTION UNION "test 1", WRAMX, BANK[2]
  db
SECTION UNION "test 1", WRAMX, BANK[3]
  db

SECTION UNION "test 2", WRAM0[$c123]
  db
SECTION UNION "test 2", WRAM0, ALIGN[1]
  db

SECTION UNION "test 3", HRAM[$ff88]
  db
SECTION UNION "test 3", HRAM[$ff99]
  db
```

3) Unions in ROM:

```
; this might be valid
SECTION UNION "test 1", ROM0
  ds $50
SECTION UNION "test 1", ROM0
  ds $100

; but this is definitely wrong
SECTION UNION "test 2", ROM0
  db 1
SECTION UNION "test 2", ROM0
  db 2

; and what about these cases...?
; there's some sensible output for all of them, but they might be too complex

SECTION UNION "test 3", ROM0
  ds 1
  db $aa
SECTION UNION "test 3", ROM0
  db $bb
  ds 1

SECTION UNION "test 4", ROM0
  ds 4
SECTION UNION "test 4", ROM0
  db $aa, $bb, $cc, $dd

SECTION UNION "test 5", ROM0
  sbc a
SECTION UNION "test 5", ROM0
  db $9f
```

4) Unsatisfiable simultaneous constraints:

```
SECTION "bloat", WRAMX[$d000], BANK]2]
  ds $fe0

SECTION UNION "test", WRAMX, BANK[2]
  db
SECTION UNION "test", WRAMX, ALIGN[6]
  db
```

**Comment by ISSOtm** [comment]
Currently, unionized sections are simply prevents in ROM due to the management it'd require. That may be changed later, but for now implementing this has been complex enough.

**Comment by aaaaaa123456789** [comment]
> Currently, unionized sections are simply prevents in ROM due to the management it'd require. That may be changed later, but for now implementing this has been complex enough.

The tests are still worthwhile IMO; you can change the desired output if you ever decide to implement ROM unions.

**Comment by ISSOtm** [comment]
Right.

**Comment by ISSOtm** [comment]
Implemented the tests above with @aaaaaa123456789's blessing.

Rebasing on current master yielded fairly complex conflicts in assertion code, which indicated that both features probably interacted poorly. More tests have been added regarding that, which produce reasonable output. (This also unveiled the logic bug fixed in 46a402f7d76dd90b668bc79c9d11b0f9f0c98e44)

Merging.

**Pull request merged**
