### PR TITLE
Prevent local symbols that are not labels

### PR DESCRIPTION
**Pull request by ISSOtm**
This should fix the problems brought up in #423.
Although this passes the test suite just fine, maybe this should not be merged for 0.3.9 because it might break some user code.

### CODE REVIEW

**Comment by ISSOtm** [comment]
Should symbols with *any* dot in their name be prevented as well?

**Comment by aaaaaa123456789** [comment]
The way I see it, dots should have never been allowed in names at all; they are used to indicate scoping for labels. RGBDS's _de facto_ current approach (dots are allowed anywhere; treat a label specially if the first character is a dot) is error-prone, as this PR proves.

**Comment by AntonioND** [comment]
> The way I see it, dots should have never been allowed in names at all; they are used to indicate scoping for labels. RGBDS's _de facto_ current approach (dots are allowed anywhere; treat a label specially if the first character is a dot) is error-prone, as this PR proves.

Agreed. Dots shouldn't be allowed.

**Comment by ISSOtm** [comment]
I think this can overlap with #457 if the grammar regarding identifiers is modified. It'll be a big undertaking though, so I'll wait on other large changes to be merged first.
Part of the problem is that dots are generally allowed but then treated specially here and there, so this change would probably affect a lot of code.

**Comment by ISSOtm** [comment]
I tried redefining the syntax to prevent `.` at all in symbol names, and making it a separate token. The problem is that Yacc considered macro definitions (`T_LABEL ':' T_POP_MACRO`) to be higher-priority than label declarations (`T_LABEL ':'`). Similarly to #457, I do not know how to fix such a shift/reduce conflict.

**Comment by AntonioND** [comment]
Yeah, I wouldn't bother having a dot as a separate token, just leave it as it is and check that the ``T_LABEL`` string doesn't have one (or, if it does, that it is a valid one, as in:

```
GlobalLabel::
    ld a,b
GlobalLabel.sublabel:
    ld b,a
.sublabel2:
    ret
```

I think that's the only thing we want to support, right?

**Comment by ISSOtm** [comment]
The problem is that `T_LABEL` is used basically in every kind of symbol definition, so it'd have to be checked everywhere.
Part of why I want to make a `T_DOT` is to still allow defining local labels without a colon if we remove colon-less labels.

**Comment by ISSOtm** [comment]
Current solution: if a symbol has a dot somewhere in it, turn it into a `T_LOCAL_ID` or `T_LOCAL_LABEL`, and only accept those in specific contexts. Upside: properly handled everywhere it's relevant. Downside: `syntax error`, but that might be improved on.

Currently debugging this, as there seems to be a problem with this in macro calls, somehow?

**Comment by ISSOtm** [comment]
This has been re-implemented by instead creating two new tokens (`T_LOCAL_{ID,LABEL}`) and using those in appropriate contexts. Using `T_DOT` causes issues with expanding string equates (all parts of the label are expanded individually instead of the label as a whole).

In effect, this does prevent using dots in anything but labels. No other symbol handling has been altered.

**Pull request merged**
