### PR TITLE
Fix __FILE__ when filename contains quotes

### PR DESCRIPTION
**Pull request by ZedKoS**

### CODE REVIEW

**Comment by ZedKoS** [comment]
Thanks for the feedback! I'll give it a more appropriate name.

**Comment by JL2210** [comment]
I wouldn't bother fixing this until the new lexer is merged; it'll just be overwritten if it is.

**Comment by ISSOtm** [comment]
Considering that #557 may not be merged in a while, I'm gonna merge this anyways. It'll have to be added to #557 separately, as JL pointed out (sigh...), and will probably trigger a merge conflict anyways.

@ZedKoS Ideally, the commit message would also be changed (`git commit --amend` suffices when it's the last one, otherwise you should use `git rebase -i`); I'm gonna squash-merge the PR to avoid the problem anyhow.

**Comment by AntonioND** [comment]
Yeah, I was talking about changing the commit message... But well, the squash merge kinda fixes the problem. Not ideal, but fair enough.

**Pull request merged**
