### PR TITLE
Enforce trailing slash in include paths

### PR DESCRIPTION
**Pull request by ISSOtm**
Fixes rednex#456

No test has been added to the suite because I'm not sure how it'd be implemented. It's not important either, is it?

### CODE REVIEW

**Comment by ISSOtm** [comment]
This segfaults for some reason on macOS. No idea why, and I lack a machine to debug it on.

**Comment by BenHetherington** [comment]
May as well appear for once, seeing as I can help here!

Looks like `rindex()` was removed in the POSIX standard we've set in the Makefile; doing `#include <strings.h>` doesn't provide its declaration (remains an implicit function declaration), and that file has those declarations wrapped in:
```c
/* Removed in Issue 7 */
#if !defined(_POSIX_C_SOURCE) || _POSIX_C_SOURCE < 200809L
int	 bcmp(const void *, const void *, size_t) __POSIX_C_DEPRECATED(200112L);
void	 bcopy(const void *, void *, size_t) __POSIX_C_DEPRECATED(200112L);
void	 bzero(void *, size_t) __POSIX_C_DEPRECATED(200112L);
char	*index(const char *, int) __POSIX_C_DEPRECATED(200112L);
char	*rindex(const char *, int) __POSIX_C_DEPRECATED(200112L);
#endif
```

The implicit declaration confuses it enough that AddressSanitizer complains on the very next line (when building µcity; perhaps due to optimisations that are required for ASan?):
```
rgbasm source/apa.asm
AddressSanitizer:DEADLYSIGNAL
=================================================================
==85900==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000100809963 bp 0x7ffeef401530 sp 0x7ffeef401520 T0)
==85900==The signal is caused by a READ memory access.
==85900==Hint: address points to the zero page.
    #0 0x100809962 in fstk_AddIncludePath fstack.c:321
    #1 0x100811cdc in main main.c:358
    #2 0x7fff6b5487fc in start (libdyld.dylib:x86_64+0x1a7fc)

==85900==Register values:
rax = 0x1ffffffffde80333  rbx = 0x00007ffeef401991  rcx = 0x1ffffffffde80333  rdx = 0x0000000000000000  
rdi = 0xffffffffef401998  rsi = 0x000000000000002f  rbp = 0x00007ffeef401530  rsp = 0x00007ffeef401520  
 r8 = 0x0000000000000000   r9 = 0x0000000000000001  r10 = 0x00007ffeef401950  r11 = 0x00007fff6b5edacc  
r12 = 0x00007ffeef401768  r13 = 0x00000000ef401500  r14 = 0x0000000100830a40  r15 = 0x00000001008255e0  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV fstack.c:321 in fstk_AddIncludePath
==85900==ABORTING
make: *** [source/apa.obj] Abort trap: 6
```

---

I should also add, trying to run with AddressSanitizer on the entire test suite gives me a crash all the way over in rgbgfx when building pokecrystal:
```
rgbgfx  -o gfx/mobile/up_arrow.2bpp gfx/mobile/up_arrow.png
=================================================================
==73104==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000218 at pc 0x00010834a312 bp 0x7ffee78b74b0 sp 0x7ffee78b74a8
READ of size 1 at 0x602000000218 thread T0
    #0 0x10834a311 in create_mapfiles gb.c:207
    #1 0x10834c45b in main main.c:334
    #2 0x7fff6b5487fc in start (libdyld.dylib:x86_64+0x1a7fc)

0x602000000218 is located 0 bytes to the right of 8-byte region [0x602000000210,0x602000000218)
allocated by thread T0 here:
    #0 0x1083f7cd7 in wrap_calloc (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x61cd7)
    #1 0x108348de8 in transpose_tiles gb.c:21
    #2 0x10834c43e in main main.c:333
    #3 0x7fff6b5487fc in start (libdyld.dylib:x86_64+0x1a7fc)

SUMMARY: AddressSanitizer: heap-buffer-overflow gb.c:207 in create_mapfiles
Shadow bytes around the buggy address:
  0x1c03fffffff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c0400000000: fa fa fd fd fa fa 00 00 fa fa 00 03 fa fa 00 06
  0x1c0400000010: fa fa 00 04 fa fa 00 00 fa fa 00 06 fa fa fd fd
  0x1c0400000020: fa fa fd fd fa fa fd fa fa fa 00 04 fa fa 00 fa
  0x1c0400000030: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa fd fa
=>0x1c0400000040: fa fa 00[fa]fa fa 00 fa fa fa 00 00 fa fa fa fa
  0x1c0400000050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==73104==ABORTING
make: *** [gfx/mobile/up_arrow.2bpp] Abort trap: 6
```

**Comment by ISSOtm** [comment]
`man 3 rindex`
> **CONFORMING TO**
>
>       4.3BSD; marked as LEGACY in POSIX.1-2001.  POSIX.1-2008 removes the
>       specifications of index() and rindex(), recommending strchr(3) and
>       strrchr(3) instead.

Should've gone further than `man strings.h` >_<'
Thanks @BenHetherington!

----

As for the ASan errors, that's interesting; I want to enable `make develop` in the CI (currently hitting a bunch of problems, more or less #283 redux, expect either a new issue or a comment on that one soon:tm:). This makes it sound like ASan is also a good candidate for enabling, though I'm worried RGBASM will lit up like a Christmas tree—at least it does under Valgrind. RGBGFX might be more handlable, but I haven't looked at it so far.

**Comment by aaaaaa123456789** [comment]
`strrchr` is the standard (as in C99 standard, perhaps C90 too?) way of doing this, so it's a net improvement.

**Comment by ISSOtm** [comment]
Now that CI passes, any oinions on this?

**Comment by AntonioND** [comment]
It looks sensible.

**Comment by ISSOtm** [comment]
Merging then!

**Comment by JL2210** [comment]
@aaaaaa123456789 `strrchr` is C90 (not that you care anymore), just found it in my copy of ISO/IEC 9899:1990: **7.11.5.2 The `strchr` function**

**Pull request merged**
