### PR TITLE
Add support for multiple charmaps

### LINKED ISSUE #256: Support Multiple Charmaps/Disable Charmap
Right now it looks like `charmap` overrides any previous mapping including ASCII. This means you can't have more than one mapping, or use ASCII and a custom map in the same ROM (eg for debug output form emulators). Would be great to have a way to specify which mapping to use for a given string or group of strings.

### PR DESCRIPTION
**Pull request by dbrotz**
This adds two new directives based on the discussion in #256 : `newcharmap` and `setcharmap`
`newcharmap name` creates a new, empty charmap called `name` and switches to it.
`newcharmap name, basename` creates a new charmap called `name` and copies the existing charmap `basename` to it.
`setcharmap name` switches to an existing charmap called `name`.

I noticed that there is an undocumented feature that creates a charmap local to the current section when you use the `charmap` directive within a section. I don't think that this feature is a good idea, especially now that we support multiple charmaps that can be freely selected. I doubt anyone was using this feature except by mistake since it was never documented and its existence is not obvious when using it.

This change preserves backward compatibility by allowing the local section charmap to override the "main" charmap, but not user-created charmaps. However, I think that this feature should be deprecated and removed in a future version, so I added a warning when using `charmap` in a section when the "main" charmap is selected as the current charmap.

Fixes #256.

### CODE REVIEW

**Comment by dbrotz** [comment]
I was thinking that having `pushcharmap` and `popcharmap` directives, similar to `pushs` and `pops` for sections, could be useful too.

In #256, this was one of the examples.
```
ascii: MACRO
    setcharmap ascii
    db \1
    setcharmap game
ENDM
```

I think it would be useful if you could do this instead.
```
ascii: MACRO
    pushcharmap
    setcharmap ascii
    db \1
    popcharmap
ENDM
```
That way you could return to whatever the charmap was previously instead of a specific one.

**Comment by ISSOtm** [comment]
Good idea, especially for macros.

**Comment by dbrotz** [comment]
Yeah. Those do fit the existing push and pop functions better. Hopefully there won't be anything we need to push/pop in the future that starts with one of the already used letters, though.

**Comment by ISSOtm** [comment]
I was thinking exactly that, but... it might indeed never happen, or we might find an alternative.
We'll figure it out in due time, won't we? :p

**Pull request merged**
