### PR TITLE
Add DESTDIR to Makefile

### PR DESCRIPTION
**Pull request by SolidTux**
Added DESTDIR to Makefile, which is used for packaging ([reference](https://www.gnu.org/prep/standards/html_node/DESTDIR.html)).

### CODE REVIEW

**Comment by AntonioND** [comment]
While at it, you could just also add $(bindir) and $(mandir). Instead of setting `PREFIX` to `${DESTDIR}/usr/local` I think it would be better to set it to ` ${DESTDIR}$(bindir)` (same for the man pages) and let the user choose the complete path if needed.

**Comment by SolidTux** [comment]
But `bindir` and `mandir` would have to be set to some default value. Or am I overlooking something?

**Comment by AntonioND** [comment]
Yeah, sure. It just feels to me that only allowing to change the start of the path and forcing to use /usr/local as the end isn't too flexible. Either we stick to /usr/local or give more flexibility.

**Comment by bentley** [comment]
When I’ve encountered DESTDIR, it wasn’t used in PREFIX‐type variables. Rather, DESTDIR is prepended to all paths in the install target.

The link you posted agrees with this usage:

    $(INSTALL_PROGRAM) foo $(DESTDIR)$(bindir)/foo
    $(INSTALL_DATA) libfoo.a $(DESTDIR)$(libdir)/libfoo.a

In addition, your latest commit removes PREFIX entirely. This is definitely not what packagers expect. PREFIX is standard; BINPREFIX and MANPREFIX are not (I made those up). bindir and mandir are better than BINPREFIX and MANPREFIX because they’re more flexible.

Please modify as follows:

* PREFIX defaults to /usr/local
* bindir defaults to ${PREFIX}/bin
* mandir defaults to ${PREFIX}/man
* Prepend ${DESTDIR} to all destination paths in the install target

**Comment by SolidTux** [comment]
Sorry for causing trouble, never did something like this before ;-)

Is the Makefile now like it should be?

**Comment by bentley** [comment]
Looks good to me.

**Comment by AntonioND** [comment]
I've squashed your commits into this one: https://github.com/rednex/rgbds/commit/bfcef01211b5cd95031db3f03771314b244852b0

**Pull request closed without merging**
