### PR TITLE
Always rebuild version.o

### PR DESCRIPTION
**Pull request by NieDzejkob**

### CODE REVIEW

**Comment by NieDzejkob** [comment]
Checking out old revisions is a harder problem to solve. It would also affect less people. The scenario this PR attempts to solve is of a user updating their installation with `git pull && make && sudo make install`, something I would expect to be relatively common among more advanced users due to the release frequency.

> If you update the repository without cleaning I don't see why the build system should guarantee that everything works.

I'd argue that this guarantee is exactly what the build system is supposed to uphold, and whether the modifications were made by `git` or `$EDITOR` shouldn't ever matter. Moreover, even if fixing this is ideologically unnecessary, users won't realize that and confusion will arise. Hence, unless a fix would be unreasonably costly, it should be applied for the purely pragmatic reason of reducing false bug reports.

**Comment by ISSOtm** [comment]
Not updating the repository without cleaning is exactly the point of incremental builds, so I'd vouch for *some* behavior to be implemented, even if it's neither this PR not AntonioND's proposal.

**Comment by ISSOtm** [comment]
Bumping this.

> For example, let's say I checkout a really old version of the repository after building the current master. I wouldn't expect make clean to work, it would leave some object files around because some files have changed their names or moved around.

`make clean` should have worked from the get-go. Due to BSD Make, .o files have to be in the source folder, which is annoying but fine, however removing .o files via a *list* sounds like a far worse idea than using globs, imo.

Honestly, considering that and [this comment](https://github.com/rednex/rgbds/issues/376#issuecomment-533928112), unless there's a simpler way (like just making `src/version.o` phony directly), I think this *is* the right thing to do.

**Comment by ISSOtm** [comment]
Trying to use this on an unrelated project of mine (but for the same purpose) caused all invocations of `make` to always rebuild the binaries. I don't think it's a good thing; that `.o` file should be made via a `make` invocation in the recipe and added to the list of objects manually, I believe.
```
rgblink: $(rgblink_obj)
    $(MAKE) $(version_obj)
    gcc -o $@ $^ $(version_obj)
```
For example?

**Comment by pinobatch** [comment]
To [avoid recursive `make`](http://aegis.sourceforge.net/auug97.pdf), you could try `.PHONY: $(version_obj)`

The [BSD Make manual](https://www.freebsd.org/cgi/man.cgi?make) states: "The target does not correspond to an actual file; it is always considered to be out of date, and will not be created with the`-t` option."

The [GNU Make manual](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html) states: "A phony target should not be a prerequisite of a real target file; if it is, its recipe will be run every time make goes to update that file." But in this case, that's exactly what you want.

```
.PHONY: $(version_obj)
rgblink: $(rgblink_obj) $(version_obj)
    gcc -o $@ $^
```

**Comment by ISSOtm** [comment]
Yes, I forgot to mention to make `version_obj` phony.

We do not want the recipe for producing the *binaries* to run on each `make` invocation, we want `version.o` to be rebuilt each time one of the binaries is rebuilt. So we don't want it to be a prerequisite.

**Comment by pinobatch** [comment]
The other way to avoid recursive `make` is not to make `$(version_obj)` phony but instead to make it depend on every object in `$(rgblink_obj)`. This way whenever any of the inputs to the linking process change, `$(version_obj)` also changes.

**Comment by ISSOtm** [comment]
But `version.o` is used by all binaries, not just `rgblink`. Making it phony is the way to go.

**Comment by mid-kid** [comment]
I see all of this talk, read very little of it, and propose just adding `version.c` (read: NOT `version.o`) and the `-D` flag to the final link command through the `gcc` frontend.

**Comment by ISSOtm** [comment]
What I was suggesting was the latter proposition, but the former sounds a lot more elegant.

**Comment by AntonioND** [comment]
I think https://github.com/rednex/rgbds/pull/465 is slightly cleaner, as it won't rebuild the object file every time you invoke make.

**Pull request closed without merging**
