### PR TITLE
Switch CI to GitHub Actions

### PR DESCRIPTION
**Pull request by ISSOtm**
As discussed in #469; the actual repo was set up as [rgbds-actions](https://github.com/ISSOtm/rgbds-actions) to avoid enabling Actions globally on my fork.

(Obviously, if this gets merged, I will disable Travis and enable Actions.)

Benefits:
- Windows regression testing (though 32-bit builds [are crippled](https://github.com/rednex/rgbds/issues/469#issuecomment-586047765))
- Building at each commit (not worth much for *nix distros, but that might enable Windows users to go bleeding-edge as well if they want)
- Better integration than Travis (for one thing, jobs that fail because of cosmic bitflips can be re-launched by a maintainer without closing+opening the issue; minor but good)
- Forks should be able to enable CI (before creating PRs) using a single config option instead 

Possible improvements:
- Enabling tests on all branches?
- Automatic HTML doc generation (see #458, some details would need to be resolved)
- Automatic release generation+packaging on tag creation (didn't bother yet, don't know how much of it can be automated)
- Testing debug+release configurations (once those are implemented)
- Removing the shell scripts in `.github/actions`. They're there because I couldn't find them upstream, and one of them—`configure`, IIRC—was straight up broken as-is.

### CODE REVIEW

**Comment by AntonioND** [comment]
Well, I really have no idea about what all this code is about and I don't have time to go through the documentation, but I'm fine with moving away from Travis CI. Not having a Windows CI was a problem. Apparently [they are working on it](https://docs.travis-ci.com/user/reference/windows/) but it's still not supported properly:

> Take note that our Windows environment is in early stages and a minimal subset of what’s available on Linux or macOS is currently supported.

**Comment by ISSOtm** [comment]
CI is failing on checkpatch complaining about C coding style errors... in shell scripts.
Merging.

**Comment by AntonioND** [comment]
I've disabled Travis CI (I think). I could keep it around for reference, or just get rid of it as it doesn't have much value to keep the build logs. Opinions?

**Comment by ISSOtm** [comment]
Oh, whoops, I didn't see the comment, so I may have jumped the gun. I honestly think there's no value in keeping the Travis files, but I can revert if anyone wants.

**Comment by ISSOtm** [comment]
Also, keeping it around for reference is useless—we just need to checkout a commit where it still exists; ain't that the point of a VCS after all? :stuck_out_tongue_winking_eye:

**Comment by aaaaaa123456789** [comment]
> I've disabled Travis CI (I think). I could keep it around for reference, or just get rid of it as it doesn't have much value to keep the build logs. Opinions?

Doesn't seem very useful. I'd just get rid of it.

**Comment by AntonioND** [comment]
Ok, I think I've removed the integration. I think...

**Comment by AntonioND** [comment]
It looks like the information is going to stay there, but Travis doesn't have access to the repo anymore.

**Comment by ISSOtm** [comment]
I think I purged Travis' access to rednex at all. Considering the [build logs](https://travis-ci.org/rednex/rgbds/builds/650245962) can still be accessed, and all Travis-related config files are still in the history, I doubt this will lose us anything.

**Comment by AntonioND** [comment]
I had to remove the webhook, but that's all.

**Pull request merged**
