### PR TITLE
Increase version number to 0.3.8

### PR DESCRIPTION
**Pull request by jmle**
Last version released is `0.3.8`, but package version still shows `0.3.7`.

### CODE REVIEW

**Comment by AntonioND** [comment]
Oh... great, I forgot. I guess I'll have to remove that tag and create another one...

**Comment by AntonioND** [comment]
It should be fine, I guess. The binaries I built all say 0.3.8 because they got the version from the git tag, so I don't actually have to replace them, I only need to update the source tarball.

**Comment by fxcoudert** [comment]
Due to the retag, `rgbds` fails to build in Homebrew now (which checks the commit reference as well as tag, for safety reasons). https://github.com/Homebrew/homebrew-core/issues/37115

Please try to stick to semantic versioning, where a version number is not reused for a different source file / source state, once it has been released.

**Comment by AntonioND** [comment]
Sorry about that. I've done it because if not there was no way to tell the two releases apart if you downloaded the tarball. I didn't know it was going to cause problems in homebrew (that check makes perfect sense).

I'm actually surprised someone uses the tarball, I imagined everyone would just clone the repository, and I was going to not provide the tarball anymore...

**Comment by bentley** [comment]
The tarball is important for packaging, because package systems generally require stable checksums. GitHub’s autogenerated tarballs are nondeterministic and can change (and have changed) in response to changes in GitHub’s backend architecture: updates to git, gzip, tar, etc. Sometimes you’ll even get different tarballs depending on your geographic location (i.e., downloading from one or another of GitHub’s CDN endpoints).

**Pull request merged**
