### PR TITLE
Add overlay to rgblink

### PR DESCRIPTION
**Pull request by Sanqui**
The overlay feature enables `rgblink` to simply place sections over an existing binary.  This is useful for partial disassemblies and also quick patches.  For disassemblies in particular, it is much more convenient than the `INCBIN` method which requires a lot of manual offset calculations.

The reason I didn't call this feature `patch` is the RGB object file format already has an unrelated feature called patches.

Overlay is already in use by the [Telefang disassembly](https://github.com/telefang/telefang).

### CODE REVIEW

**Comment by AntonioND** [comment]
So basically this takes a preexisting file and assembles stuff on top of it instead of starting with empty space, right?

**Comment by Sanqui** [comment]
Correct.

**Comment by Ben10do** [comment]
#125 might've thrown a spanner in the works here...

**Comment by AntonioND** [comment]
Well, one of them was going to block the other one, and I thought that the alignment of sections was long overdue...

**Comment by Sanqui** [comment]
Whoops!  This shouldn't be too hard to fix, though.  Currently overlay only works when all ROMX sections are fixed, anyway.  I'll take a look later.

**Comment by Sanqui** [comment]
I have resolved the conflict, and also corrected a slight oversight.

**Comment by AntonioND** [comment]
I've been taking a look at this... Shouldn't ALL sections be fixed? Not just the ROM section.

**Comment by Sanqui** [comment]
I suppose if you're making a disassembly, you will usually use fixed sections even in RAM.  But my thought process is that you might want to add sections in e.g. empty banks which you'll let `rgbds` place anywhere.

**Comment by AntonioND** [comment]
But then you have to disassemble everything to know the areas of RAM that are being used by the game and create sections there so that rgblink doesn't try to use the same memory for the new variables. The same thing could be said of ROM banks. It seems a bit inconsistent to have both behaviours.

**Comment by Sanqui** [comment]
I get your point. I'll amend the behavior.

**Comment by Ben10do** [comment]
Perhaps you could use separate flags to either enable or disable the restriction that all sections should be fixed? For example, you could use `-F` to force fixed sections and `-f` to allow floating sections.

In this context, you'd use `-O` for an overlay (implicitly forcing fixed sections), and `-Of` for an overlay allowing floating sections.

With this, you'd begin a disassembly using `-O` to ensure that sections are fixed, and once it's reached a complete enough state, you can use `-Of` to allow for new floating sections.

**Comment by AntonioND** [comment]
I like the idea.

**Comment by Sanqui** [comment]
I'm not convince there can be a "complete enough state" that still requires the original file to be present.

I'd rather always allow for floating sections but have them placed after the overlay file (making the ROM size bigger), or possibly in space somehow defined as empty.  I considered that out of scope for now though.

**Comment by AntonioND** [comment]
That makes sense, let's go for "all sections must be fixed". You just can't know which WRAM regions are used until you disassemble the ROM completely, so I don't think it makes sense for them to be allowed to be floating.

**Comment by Sanqui** [comment]
Got around making this slight change.

**Pull request merged**
